// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-ZPuxxc13xA88Rhl_KlAd5whwL0shx9c',
    appId: '1:75353642932:web:4daeeceb0e2f7cc91204e1',
    messagingSenderId: '75353642932',
    projectId: 'api-login-78da7',
    authDomain: 'api-login-78da7.firebaseapp.com',
    storageBucket: 'api-login-78da7.firebasestorage.app',
    measurementId: 'G-V1NG26ZSWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArpeeXcE3uTPL_z2epfqZSqc5K8QKnuqE',
    appId: '1:75353642932:android:d9a62196e4cc20551204e1',
    messagingSenderId: '75353642932',
    projectId: 'api-login-78da7',
    storageBucket: 'api-login-78da7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXVrUS3UdgsSJRnWT5tcRgmxFR8NVSUtg',
    appId: '1:75353642932:ios:bdd514a914b8793a1204e1',
    messagingSenderId: '75353642932',
    projectId: 'api-login-78da7',
    storageBucket: 'api-login-78da7.firebasestorage.app',
    iosBundleId: 'com.example.stylemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXVrUS3UdgsSJRnWT5tcRgmxFR8NVSUtg',
    appId: '1:75353642932:ios:bdd514a914b8793a1204e1',
    messagingSenderId: '75353642932',
    projectId: 'api-login-78da7',
    storageBucket: 'api-login-78da7.firebasestorage.app',
    iosBundleId: 'com.example.stylemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-ZPuxxc13xA88Rhl_KlAd5whwL0shx9c',
    appId: '1:75353642932:web:4daeeceb0e2f7cc91204e1',
    messagingSenderId: '75353642932',
    projectId: 'api-login-78da7',
    authDomain: 'api-login-78da7.firebaseapp.com',
    storageBucket: 'api-login-78da7.firebasestorage.app',
    measurementId: 'G-V1NG26ZSWM',
  );

}